source 'https://rubygems.org'

gem "jekyll", "~> 4.3.2"
gem "jekyll-remote-theme"
gem "jekyll-seo-tag"

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end